services:
  web:
    build: .
    container_name: cinema_web
    entrypoint: ["bash", "/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2
    container_name: cinema_db
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema"]
      interval: 5s
      retries: 20
      timeout: 5s
      start_period: 10s

volumes:
  postgres_data:

